#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint:fix && npm run format && npm test
current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$current_branch" != "rss-puzzle" ]; then
  npx validate-branch-name
fi
